air-name: '&7AirDrop'
id: example
world: world
time-to-start: 120
time-to-open: 120
time-to-end: 120
use-static-loc: false
static-loc:
  x: 0
  y: 0
  z: 0
triggered-time-to-open: true
independent-time-to-end: false
material-when-closed: RESPAWN_ANCHOR
material-when-opened: ENDER_CHEST
required-number-of-players-online: 1
enable: true
signed-listeners:
- default:activate
- default:open
- default:start
- default:end
- default:holoTimeToOpen-updater
- default:hologramTimeStart-updater
- default:click_open
- default:click_close
- default:spawn_message
- default:summoned
- default:hologramTimeToEnd-updater
use-default-timer: true
