#   alert-5:
#    icon: OBSERVER
#    description: '&fMessage about opening in 5 seconds'
#    event: 'start'
#    requirement:
#      check-1:
#        type: 'math'
#        input: '{time-to-open} == 5'
#      check-2:
#        type: 'string'
#        input: 'str equals str' # can be !equals, '==' and '!='
#      check-3:
#        type: 'string'
#        input: 'strstr contains str' # can be !contains
#    commands:
#      - '[MESSAGE_ALL] {air-name}&7 will open in 5 seconds'
#    deny-commands:
#      - 'deny'
listeners:
   test:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] {air_name}&f time_to_start={time_to_start}, time_to_open={time_to_open}, time_to_end={time_to_end} x={x}, y={y}, z={z} '

   test-1:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-2:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-3:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-4:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-5:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-6:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-7:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-8:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-9:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-10:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-11:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-12:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-13:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-14:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-15:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-16:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-17:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-18:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-19:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-20:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-21:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-22:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-23:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-24:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-25:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-26:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-27:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-28:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-29:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-30:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-31:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-32:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-33:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-34:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-35:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-36:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-37:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-38:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-39:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-40:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-41:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-42:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-43:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-44:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-45:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-46:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-47:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-48:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-49:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-50:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-51:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-52:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-53:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-54:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-55:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-56:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-57:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-58:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-59:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'
   test-60:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] 1'