#   alert-5:
#    icon: OBSERVER
#    description: '&fMessage about opening in 5 seconds'
#    event: 'start'
#    requirement:
#      check-1:
#        type: 'math'
#        input: '{time-to-open} == 5'
#      check-2:
#        type: 'string'
#        input: 'str equals str' # can be !equals, '==' and '!='
#      check-3:
#        type: 'string'
#        input: 'strstr contains str' # can be !contains
#    commands:
#      - '[MESSAGE_ALL] {air-name}&7 will open in 5 seconds'
#    deny-commands:
#      - 'deny'
listeners:
   test:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] {air_name}&f time_to_start={time_to_start}, time_to_open={time_to_open}, time_to_end={time_to_end} x={x}, y={y}, z={z} '