#   alert-5:
#    icon: OBSERVER
#    description: '&fMessage about opening in 5 seconds'
#    event: 'start'
#    requirement:
#      check-1:
#        type: 'math'
#        input: '{time-to-open} == 5'
#      check-2:
#        type: 'string'
#        input: 'str equals str' # can be !equals, '==' and '!='
#      check-3:
#        type: 'string'
#        input: 'strstr contains str' # can be !contains
#    commands:
#      - '[MESSAGE_ALL] {air-name}&7 will open in 5 seconds'
#    deny-commands:
#      - 'deny'
listeners:
   test:
    icon: OBSERVER
    description: '&fMessage about opening in 5 seconds'
    event: 'tick'
    commands:
      - '[MESSAGE_ALL] {air_name}&f time_to_start={time_to_start}, time_to_open={time_to_open}, time_to_end={time_to_end} x={x}, y={y}, z={z} '

   click_open:
     description: '&fоткрывает инвентарь аирдропа игроку'
     event: 'click_open'
     commands:
       - '[INV_MANAGER] [OPEN_INVENTORY]'

   click_close:
     description: '&fоткрывает инвентарь аирдропа игроку'
     event: 'click_close'
     commands:
       - '[MESSAGE] &cАирдроп закрыт!'


   open:
     description: '&fоткрывает инвентарь аирдропа игроку'
     event: 'open'
     commands:
       - '[INV_MANAGER] [GENERATE_LOOT]'
       - '[HOLOGRAM] [REMOVE] holo1'
       - '[HOLOGRAM] [CREATE] hologramTimeToEnd holo2'

   end:
     description: '&fоткрывает инвентарь аирдропа игроку'
     event: 'end'
     commands:
       - '[INV_MANAGER] [CLEAR_INVENTORY]'
       - '[REMOVE_REGION]'
       - '[EFFECT_STOP] newEffect'
       - '[HOLOGRAM] [REMOVE] holo2'

   start:
     description: '&fStart'
     event: 'start'
     commands:
       - '[SET_REGION]'
       - '[MESSAGE_ALL] {air_name} Заспавнился!'
       - '[EFFECT_START] circle newEffect'
       - '[HOLOGRAM] [CREATE] hologramTimeToOpen holo1'


   holo1-updater:
     description: '&fHolo updater'
     event: 'tick'
     requirement:
       check:
         type: 'math'
         input: '{started} && !{opened}'
     commands:
       - '[HOLOGRAM] [UPDATE] holo1'

   holo2-updater:
     description: '&fHolo updater'
     event: 'tick'
     requirement:
       check:
         type: 'math'
         input: '{opened}'
     commands:
       - '[HOLOGRAM] [UPDATE] holo2'