#   alert-5:
#    icon: OBSERVER
#    description: '&fMessage about opening in 5 seconds'
#    event: 'start'
#    requirement:
#      check-1:
#        type: 'math'
#        input: '{time-to-open} == 5'
#      check-2:
#        type: 'string'
#        input: 'str equals str' # can be !equals, '==' and '!='
#      check-3:
#        type: 'string'
#        input: 'strstr contains str' # can be !contains
#    commands:
#      - '[MESSAGE_ALL] {air-name}&7 will open in 5 seconds'
#    deny-commands:
#      - 'deny'
listeners:
  spawn_message:
    icon: OBSERVER
    description: '&Сообщение о спавне за 30, 20, 10, 5...1 секунд'
    event: 'tick'
    requirement:
      check-1:
        type: 'math'
        # Это условие проверяет что до старта осталось 30 или 20 или 10 или 5...1 секунд. Вы можете делать более простые условие например {time_to_start} == 10
        input: '({time_to_start} <= 30 && {time_to_start} % 10 == 0 || {time_to_start} <= 5) && {time_to_start} != 0'
    commands:
      - '[MESSAGE_ALL] {air_name}&f Появится через {time_to_start} сек.'


  start:
    description: '&fОсновной слушатель на спавн аирдропа'
    event: 'start'
    commands:
      - '[SET_REGION]'
      - '[MESSAGE_ALL] {air_name}&f Появился!'
      - '[MESSAGE_ALL] На координатах x:{x} y:{y} z:{z}'
      - '[EFFECT_START] random_particle rnd_particles'
      - '[HOLOGRAM] [CREATE] hologramClickWait holoClickWait'
      - '[HOLOGRAM] [REMOVE] holoTimeStart -ifexist' # если аирдроп был призван маяком

  activate:
    icon: OBSERVER
    description: '&Слушает активацию аирдропа'
    event: 'activate'
    commands:
      - '[MESSAGE_ALL] &fИгрок %player_name%&f активировал {air_name}!'
      - '[HOLOGRAM] [CREATE] hologramTimeToOpen holoTimeToOpen'
      - '[HOLOGRAM] [REMOVE] holoClickWait'
      - '[EFFECT_START] circle circle_particles'

  holoTimeToOpen-updater:
    description: '&fОбновляет голограмму holoTimeToOpen'
    event: 'tick'
    requirement:
      check:
        type: 'math'
        input: '{started} && {clicked} && !{opened}'
    commands:
      - '[HOLOGRAM] [UPDATE] holoTimeToOpen'

  click_open:
    description: '&fОткрывает инвентарь аирдропа игроку'
    event: 'click_open'
    commands:
      - '[INV_MANAGER] [OPEN_INVENTORY]'

  click_close:
    description: '&fСообщение игроку о том что аирдроп закрыт'
    event: 'click_close'
    commands:
      - '[MESSAGE] &cАирдроп закрыт!'

  open:
    description: '&fГенерирует лут в аирдропе'
    event: 'open'
    commands:
      - '[INV_MANAGER] [GENERATE_LOOT]'
      - '[HOLOGRAM] [REMOVE] holoTimeToOpen'
      - '[HOLOGRAM] [CREATE] hologramTimeToEnd holoTimeToEnd'

  end:
    description: '&fоткрывает инвентарь аирдропа игроку'
    event: 'end'
    commands:
      - '[INV_MANAGER] [CLEAR_INVENTORY]'
      - '[REMOVE_REGION]'
      - '[EFFECT_STOP_ALL]'
      - '[HOLOGRAM] [REMOVE] holoTimeToEnd -ifexist' # На всякий случай пытаемся удалить все голограммы
      - '[HOLOGRAM] [REMOVE] holoTimeToOpen -ifexist'
      - '[HOLOGRAM] [REMOVE] holoTimeToStart -ifexist'
      - '[HOLOGRAM] [REMOVE] holoClickWait -ifexist'
      - '[HOLOGRAM] [REMOVE] holoTimeStart -ifexist'

  hologramTimeToEnd-updater:
    description: '&fОбновляет голограмму holoTimeToOpen'
    event: 'tick'
    requirement:
      check:
        type: 'math'
        input: '{started} && {opened}'
    commands:
      - '[HOLOGRAM] [UPDATE] holoTimeToEnd'

  hologramTimeStart-updater:
    description: '&fОбновляет голограмму holoTimeStart'
    event: 'tick'
    requirement:
      check:
        type: 'math'
        input: '{summoned} && !{started}'
    commands:
      - '[HOLOGRAM] [UPDATE] holoTimeStart'

  summoned:
    description: '&fСлушает призыв аирдропа'
    event: 'summoned'
    commands:
      - '[LOGG] summoned!'
      - '[SET_MATERIAL] SOUL_CAMPFIRE'
      - '[SET_REGION]'
      - '[SET_TIME_TO_START] 30'
      - '[HOLOGRAM] [CREATE] hologramTimeStart holoTimeStart'
      - '[MESSAGE_ALL] Игрок %player_name% призвал аирдроп {air_name}!'
      - '[MESSAGE_ALL] На координаты x:{x} y:{y} z:{z}'