name: BAirDropX
version: '${project.version}'
main: org.by1337.bairx.BAirDropX
api-version: '1.16'
depend:
  - BLib
  - WorldGuard
  - WorldEdit
commands:
  bairdropx:
    aliases:
      - bairx
      - bair
      - air
      - airdrop